### ISSUE TITLE
Crash on app launch — probably because of thousands of messages fetched

### ISSUE THREAD

**Issue by asmexcaliburwoods** [matrix-org/matrix-android-console#1]
I launch the matrix app for android, and it crashes probably because of thousands of messages fetched from matrix.org server (I am subscribed to some rooms with a lot of traffic). My hardware is Sony Xperia Z Ultra, model C6833, OS: Android 4.3.

**Comment by asmexcaliburwoods** [comment]
Before that (when the message counts were small), the app was working OK.

**Comment by asmexcaliburwoods** [comment]
Matrix Console version 0.4.3 is installed on my device.

**Comment by asmexcaliburwoods** [comment]
The current http://matrix.org/jenkins/job/AndroidConsoleDevelop/lastSuccessfulBuild/artifact/console/build/outputs/apk/console-alpha-debug.apk does not crash.

**Comment by ylecollen** [comment]
It should be fixed by now.
