### ISSUE TITLE
Hold press to download sent pictures.

### ISSUE THREAD

**Issue by d6e** [matrix-org/matrix-android-console#12]
In other matrix clients like vector.im, you can right click on a sent image and download it. Could we get a feature where you can hold press on a sent picture to download it?

**Comment by ylecollen** [comment]
I assume you talk about the vector.im webclient.
It is possible to do the same thing on the android client
1 - tap on the image to display it : its download should start.
2 - When the download is finished, leave the full screen display and tap on the image side (not on the image itself) : a menu should be displayed with a SAVE entry.
