### ISSUE TITLE
When message is read on other device, remove notification

### ISSUE THREAD

**Issue by mitchhentges** [matrix-org/matrix-android-console#15]
**To reproduce**
1. Join channel as some user A on the `matrix-android-console`, then minimize the app
2. Join channel as user A on [vector.im](https://vector.im)
3. Join channel as user B on [vector.im](https://vector.im)
4. As user B, send "test"
5. A notification should appear on the android device. This is good and working as intended
6. Read the message on [vector.im](https://vector.im) as user A
7. From user B's perspective, A has read the message (read receipts show that the message is read)
8. The notification should have gone away on the `matrix-android-console`, because the message was read by the logged-in-user, **but the notification is still there**

Slack does this nicely. When I get caught up reading a channel's messages on the Web app, the Android app puts the relevant notifications away

**Comment by ylecollen** [comment]
It has been fixed on
https://github.com/matrix-org/matrix-android-console/commit/618f9a83
