### ISSUE TITLE
Add support for Android Auto

### ISSUE THREAD

**Issue by friedger** [matrix-org/matrix-android-console#8]
There was a basic implementation for Android Auto support in the previous app in the matrix-android-sdk. This could be easily copied over to here.

**Comment by ylecollen** [comment]
friedger,
You are right : there was an Android Auto support in the SDK but the client was rejected to the google play certification. 
We prefer implementing a nice android client for phones and tablets before adding car support. We are only few developers so we made some choices.

**Comment by friedger** [comment]
@ylecollen With Android Auto available on phones (as announced at Google I/O 2016), I am happy to send a pull request. Does it have a chance to get merged?
